// calendar
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE'

// reminders
export const ADD_REMINDER = 'ADD_REMINDER'
export const SET_REMINDER_FORM_VISIBILITY = 'SET_REMINDER_FORM_VISIBILITY'
export const SET_REMINDER_FORM_TYPE = 'SET_REMINDER_FORM_TYPE'
