// calendar
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE'

// reminders
export const ADD_REMINDER = 'ADD_REMINDER'
export const SET_REMINDER = 'SET_REMINDER'
export const SET_REMINDER_FORM_VISIBILITY = 'SET_REMINDER_FORM_VISIBILITY'
export const SET_REMINDER_FORM_TYPE = 'SET_REMINDER_FORM_TYPE'
export const SET_REMINDER_FORM_INITIAL_VALUES = 'SET_REMINDER_FORM_INITIAL_VALUES'
export const SET_REMINDER_FORECAST = 'SET_REMINDER_FORECAST'
